#!/usr/bin/env node
// npm run brand <id>
//
// Points the app at brands/<id>/: writes src/brand/current.ts (config and
// logos) and copies brands/<id>/android/res (launcher icons, if the brand has
// them) into the Android flavor's res folder. The Android flavors themselves
// are generated from brands/*/brand.json by android/app/build.gradle.

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const id = process.argv[2];

if (!id) {
  const ids = fs
    .readdirSync(path.join(root, 'brands'))
    .filter(d => fs.existsSync(path.join(root, 'brands', d, 'brand.json')));
  console.error(`Usage: npm run brand <id>\nBrands: ${ids.join(', ')}`);
  process.exit(1);
}

const dir = path.join(root, 'brands', id);
const configPath = path.join(dir, 'brand.json');
if (!fs.existsSync(configPath)) {
  console.error(`brands/${id}/brand.json not found`);
  process.exit(1);
}

const brand = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const required = ['id', 'name', 'apiUrl', 'palette', 'storageFolder', 'android'];
const missing = required.filter(key => !brand[key]);
if (missing.length) {
  console.error(`brands/${id}/brand.json is missing: ${missing.join(', ')}`);
  process.exit(1);
}
if (!fs.existsSync(path.join(dir, 'logo.png'))) {
  console.error(`brands/${id}/logo.png is required`);
  process.exit(1);
}

const hasDarkLogo = fs.existsSync(path.join(dir, 'logo-dark.png'));
const current = `// Generated by \`npm run brand ${id}\`. Do not edit by hand.
import type { Brand } from './types';
import config from '@brands/${id}/brand.json';

export const brand = config as Brand;
export const logo = require('@brands/${id}/logo.png');
export const logoDark: number | null = ${hasDarkLogo ? `require('@brands/${id}/logo-dark.png')` : 'null'};
`;
fs.writeFileSync(path.join(root, 'src', 'brand', 'current.ts'), current);

const resSrc = path.join(dir, 'android', 'res');
if (fs.existsSync(resSrc)) {
  const resDest = path.join(root, 'android', 'app', 'src', id, 'res');
  fs.mkdirSync(resDest, {recursive: true});
  fs.cpSync(resSrc, resDest, {recursive: true});
  console.log(`Copied launcher resources to android/app/src/${id}/res`);
}

const flavor = id.charAt(0).toUpperCase() + id.slice(1);
console.log(`Brand set to ${brand.name} (${brand.android.applicationId}).`);
console.log(`Build with: cd android && ./gradlew assemble${flavor}Release`);
