// Generated by `npm run brand evi`. Do not edit by hand.
// The web version of current.ts: images are imported, so the bundler gives
// each one a URL (the phone's `require` does not exist in a browser).
import type {Brand} from './types';
import config from '@brands/evi/brand.json';
import logoUrl from '@brands/evi/logo.png';
import logoDarkUrl from '@brands/evi/logo-dark.png';

export const brand = config as Brand;
export const logo = logoUrl as unknown as number;
export const logoDark: number | null = logoDarkUrl as unknown as number;
