// Generated by `npm run brand evi`. Do not edit by hand.
import type {Brand} from './types';
import config from '@brands/evi/brand.json';

export const brand = config as Brand;
export const logo = require('@brands/evi/logo.png');
export const logoDark: number | null = require('@brands/evi/logo-dark.png');
